server {
    listen       80;
    server_name  localhost;

    charset utf-8;

    # Configuração principal para SPA React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esta linha faz o roteamento client-side (React Router) funcionar ao invés de dar 404
        try_files $uri $uri/ /index.html;
    }

    # Evitar log de favicon
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    # Tratar erros
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
